# Generated by Django 5.2 on 2025-05-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mood', models.CharField(choices=[('very_happy', 'Very Happy'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('stressed', 'Stressed')], max_length=12)),
                ('anxiety_level', models.PositiveSmallIntegerField(default=1, help_text='1 (low) to 10 (high)')),
                ('stress_level', models.PositiveSmallIntegerField(default=1, help_text='1 (low) to 10 (high)')),
                ('energy_level', models.PositiveSmallIntegerField(default=5, help_text='1 (exhausted) to 10 (energized)')),
                ('focus_level', models.PositiveSmallIntegerField(default=5, help_text='1 (distracted) to 10 (laser focus)')),
                ('notes', models.TextField(blank=True)),
                ('medication_taken', models.BooleanField(default=False)),
                ('medication_notes', models.TextField(blank=True, help_text='Dosage, time, effect notes…')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mental health entries',
                'ordering': ['-date'],
            },
        ),
    ]
